language: go
sudo: false
go:
- '1.10'
script:
- make
before_deploy:
- make VERSION=${TRAVIS_TAG} release -j2
deploy:
  provider: releases
  api_key:
    secure: jIyN3VG72HEp/7Fw+HlTlzOZMFfo7zsUQUPmBj8uxVVxAZ8R9Z+pbYMXUhHX2UjCEs5Q2qeM8f4DzVDB9IIbX/r11ZxBV4Xy2sij/3/BpXsgARAL7lxMr/keXueC854Ki7fjyIrg/7BZ6//Sd7EviuUi2GgX11fYYXzUMJpnU7a3zFBxERrPn5+WFHpe/t4MXxcnmlyQ8gqvPo2U5ELQdD9wnxbcoV7n+V98jGjWe6lF+gLn+nabL5/79SdahAedkcIgPwCFL/tX2XtS+8XOuthE41GP9SvAcNXz8ZdYT/U7Grg6uJE13XrOIQL9/+wFo3PDLmCSxfv5C91rMZaCgTqhtN+gHecE7N84Nu/aMQ0Q5Fhq3Zww8lfVGKQzGIzTtO4brivmP1wsM8q0kDwUAdv2WjbmPK0Jn5YgSOfDPcxES2ndDZBM/un9dtGe4UOmgQn/drCHikKJGGdVltpf6fzLqBl5dKmAHbGuQnVuThn0Nqr+6BANMJTyKNWfcu5j7pjMtyX0afLy54kzqQ78ygBcDKEdgRZd0Bcno3bXT9V5O2V3q4c9A8EYKQfKqdeSkO9IA61wEmo+fiN1kftmeLLap04HbJHg4DmtA3fyYvV7hlPcUQGc3Hm6+yzzjlJ67UuQbqfCFR3fAvVFikESUskH+Sl2U4iWApjmPLOQxlo=
  file: release/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: crossid/tiny-static-server
